Merge pull request #19 from Rha02/main
Rha02/spark-art pull request #20
Opened 2024-09-30 06:05 UTC by mic0430

Login UI pull request

2024-09-30 18:18 UTC, Rha02 requested changes
There are no code changes in this PR.

Update the Login UI then push your changes to this branch

2024-09-30 18:59 UTC, Rha02 requested changes
Look at comments I left

2024-09-30 18:59 UTC, Rha02 commented on frontend/src/app/login/page.tsx
> +            {error && <p style={{ color: "red" }}>{error}</p>}
Use TailwindCSS.
Make it look a lot more like the form in the Register page

2024-09-30 18:59 UTC, Rha02 commented on frontend/src/app/login/page.tsx
> +    const router = useRouter();
Unnecessary `useState`. No need for state variables.

2024-09-30 18:59 UTC, Rha02 commented on frontend/src/app/login/page.tsx
> +        const res = await fetch("/api/login", {
Refer to the handleSubmit function in the Register page. Get username and password from the form rather than using state variables

2024-10-25 13:23 UTC, mic0430 commented
"Login Page"

2024-10-29 00:13 UTC, Rha02 approved these changes
Looks good to me!

2024-10-29 00:13 UTC, merged